`timescale 1ns / 1ps

module neuronlink_router_fpga_top (
    input wire clk,         // Board clock (e.g., ZCU106 200 MHz)
    input wire rst_n        // Board reset (active low, e.g., pushbutton)
    // No explicit output, everything is viewed via ILA
);

    // Parameters
    localparam DATA_WIDTH = 32;
    localparam VC_COUNT   = 4;
    localparam VC_DEPTH   = 4;
    localparam PORT_COUNT = 5;
    localparam FIFO_DEPTH = 4;
    localparam ROUTER_X   = 1;
    localparam ROUTER_Y   = 1;

    // Static input: Send one packet out Local port
    wire [PORT_COUNT-1:0] in_valid = 5'b10000; // Only Local valid
    wire [PORT_COUNT-1:0][DATA_WIDTH-1:0] in_data;
    assign in_data[0] = 0; // N
    assign in_data[1] = 0; // E
    assign in_data[2] = 0; // S
    assign in_data[3] = 0; // W
    // Local: dest_x = 2, dest_y = 1, payload = 0x1234abcd
    assign in_data[4] = {24'h1234ab, 8'b0_010_001_0}; // [7:0]=header for (2,1)

    wire [PORT_COUNT-1:0] in_ready;
    wire [PORT_COUNT-1:0] out_valid;
    wire [PORT_COUNT-1:0][DATA_WIDTH-1:0] out_data;
    wire [PORT_COUNT-1:0] out_ready = 5'b11111; // Always ready

    neuronlink_router #(
        .DATA_WIDTH(DATA_WIDTH),
        .VC_COUNT(VC_COUNT),
        .VC_DEPTH(VC_DEPTH),
        .PORT_COUNT(PORT_COUNT),
        .FIFO_DEPTH(FIFO_DEPTH),
        .ROUTER_X(ROUTER_X),
        .ROUTER_Y(ROUTER_Y)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .in_valid(in_valid),
        .in_data(in_data),
        .in_ready(in_ready),
        .out_valid(out_valid),
        .out_data(out_data),
        .out_ready(out_ready)
    );

    // Flatten out_data [5][32] to [160]
    wire [159:0] out_data_flat = {out_data[4], out_data[3], out_data[2], out_data[1], out_data[0]};

    // ILA instantiation (generated by Vivado IP Integrator or IP Catalog)
    // Make sure your ILA IP core is named "ila_0" or adjust accordingly.
    ila_0 u_ila (
        .clk(clk),
        .probe0(out_valid),      // [4:0]
        .probe1(out_data_flat)   // [159:0]
        // Add more probes if you configured more in the ILA IP
    );

endmodule